id: IE64C0ADE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T00:29:09+00:00'
last_modified: '2022-06-07T12:44:41.669649+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29983
  title: འབུམ་ནག་གསལ་སྒྲོན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CDDB:
      image_group_id: I1PD409
      title: ''
      total_pages: 404
      order: 1
      base_file: CDDB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
